### ISSUE TITLE
AdWords conversion value

### ISSUE THREAD

**Issue by dc006** [fooman/googleanalyticsplus#99]
I wonder if the googleanalyticsplus is supposed to send conversion value to AdWords when Google Dynamic Remarketing is enabled.
I see number of conversions but conversion value.

If this data are not passed, why not? I understand that primary objective of remarketing is to send data about pages/products visited nevertheless conversion value is also useful for defining audience for remarketing

**Comment by dc006** [comment]
When I check my page with TAG ASSISTANT RECORDINGS i see duplicated remarketing tag.
One tag contains conversion value var google_conversion_value = 0.5500; and the other contains "ecomm_totalvalue": "0.55"

Nevertheless the conversion value in adwords is shown as 0 (zero) 
Iam not sure what is happening here.

![screenclip646464](https://cloud.githubusercontent.com/assets/6514659/19786413/1d60254e-9c9e-11e6-8bec-9d80bfa7ba17.png)

![screenclip456464](https://cloud.githubusercontent.com/assets/6514659/19786582/f7a3d282-9c9e-11e6-9857-3bd55a71b02b.png)

![screenclip454646](https://cloud.githubusercontent.com/assets/6514659/19786587/fbabad82-9c9e-11e6-8882-5bf7f3686257.png)

**Comment by fooman** [comment]
There are various different conversion values that are tracked (adword conversion but you were also seeing the tag manager value). As this issue has dated quite a bit I am closing it now. If this issue is still present in the latest releases please re-open with further info and what you believe should be sent instead (from the above info it looks like information is sent but maybe not to what is expected on the adwords end).
